# Generated by Django 6.0.5 on 2026-05-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0003_flexible_framework_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customization_details',
            field=models.JSONField(blank=True, default=dict, help_text='{"engraving": "Text", "box_color": "natur", "selected_design": "elegant"}'),
        ),
        migrations.AddField(
            model_name='order',
            name='occasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.occasion'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_customization',
            field=models.JSONField(blank=True, default=dict, help_text='{"engraving_text": "...", "selected_design": "elegant", "box_color": "natur"}'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.productvariant'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
    ]
