# Generated by Django 6.0.5 on 2026-05-12 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('box_type', models.CharField(choices=[('audio', 'Hörbox (Audio-Aufnahmen)'), ('wood', 'Holzbox (Cards only)'), ('hybrid', 'Hybrid (Audio + Cards)')], default='audio', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('weight_grams', models.PositiveIntegerField(default=0, help_text='Gewicht in Gramm')),
                ('dimensions', models.JSONField(blank=True, default=dict, help_text='{"length": 20, "width": 15, "height": 10}')),
                ('features', models.JSONField(blank=True, default=list, help_text='["USB-C", "LED-Anzeige"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Box-Typ',
                'verbose_name_plural': 'Box-Typen',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='Gift', help_text='Lucide icon name', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Standard-Anlass für den Shop')),
                ('color_primary', models.CharField(default='#d4a574', help_text='Hex-Farbe z.B. #d4a574', max_length=7)),
                ('color_secondary', models.CharField(default='#8b7355', help_text='Hex-Farbe z.B. #8b7355', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anlass',
                'verbose_name_plural': 'Anlässe',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CardPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('card_count', models.PositiveIntegerField(help_text='Anzahl der Karten')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('available_designs', models.JSONField(blank=True, default=list, help_text="['elegant', 'modern', 'rustic']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occasions', models.ManyToManyField(blank=True, related_name='card_packages', to='products.occasion')),
            ],
            options={
                'verbose_name': 'Kartenpaket',
                'verbose_name_plural': 'Kartenpakete',
                'ordering': ['sort_order', 'card_count'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Auto-generiert wenn leer', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Überschreibe den berechneten Preis', max_digits=8, null=True)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Zuschlag zum berechneten Preis (positiv oder negativ)', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Standard-Variante für schnellen Kauf')),
                ('image', models.ImageField(blank=True, upload_to='products/variants/')),
                ('customization_options', models.JSONField(blank=True, default=dict, help_text='{"engraving": true, "color_choice": ["natur", "dunkel"], "message_card": true}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='products.boxtype')),
                ('card_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='products.cardpackage')),
                ('occasion', models.ForeignKey(blank=True, help_text='Optional: Spezifischer Anlass, oder universell wenn leer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.occasion')),
            ],
            options={
                'verbose_name': 'Produkt-Variante',
                'verbose_name_plural': 'Produkt-Varianten',
                'ordering': ['box_type__sort_order', 'card_package__card_count'],
                'unique_together': {('box_type', 'card_package', 'occasion')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='migrated_to_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_product', to='products.productvariant'),
        ),
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/variants/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.productvariant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OccasionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('hero_title', 'Hero Titel'), ('hero_subtitle', 'Hero Untertitel'), ('hero_description', 'Hero Beschreibung'), ('product_title', 'Produkt-Bereich Titel'), ('product_description', 'Produkt-Bereich Beschreibung'), ('box_audio_title', 'Audio-Box Titel'), ('box_audio_description', 'Audio-Box Beschreibung'), ('box_wood_title', 'Holz-Box Titel'), ('box_wood_description', 'Holz-Box Beschreibung'), ('cta_title', 'CTA Titel'), ('cta_description', 'CTA Beschreibung')], max_length=50)),
                ('content', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True, verbose_name='Content (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/occasions/')),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='products.occasion')),
            ],
            options={
                'verbose_name': 'Anlass-Inhalt',
                'verbose_name_plural': 'Anlass-Inhalte',
                'unique_together': {('occasion', 'key')},
            },
        ),
    ]
