# Generated by Django 6.0.5 on 2026-05-07 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('anchor', models.SlugField(unique=True)),
                ('template_type', models.CharField(choices=[('hero', 'Hero – Vollbild mit Titel & CTA'), ('text_image_left', 'Text + Bild (Bild links)'), ('text_image_right', 'Text + Bild (Bild rechts)'), ('features_grid', 'Features-Grid (3 oder 4 Spalten)'), ('testimonials', 'Testimonials / Bewertungen'), ('faq', 'FAQ Accordion'), ('gallery', 'Bildgalerie'), ('timeline', 'Timeline / Ablauf'), ('countdown', 'Countdown Timer'), ('video', 'Video Embed (YouTube/Vimeo)'), ('pricing', 'Pricing-Tabelle'), ('contact', 'Kontakt-Formular')], max_length=50)),
                ('content', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Custom Section',
                'verbose_name_plural': 'Custom Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sections/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.customsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
