# Generated by Django 6.0.5 on 2026-05-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_customsection_sectionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsection',
            name='site_contents',
            field=models.ManyToManyField(blank=True, related_name='custom_sections', to='content.sitecontent', verbose_name='Zugeordnete Seiteninhalte'),
        ),
    ]
