# Generated by Django 6.0.5 on 2026-05-12 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_site_contents_to_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('template', models.CharField(choices=[('default', 'Standard'), ('landing', 'Landingpage'), ('shop', 'Shop')], default='default', max_length=50)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('show_in_nav', models.BooleanField(default=False)),
                ('nav_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seite',
                'verbose_name_plural': 'Seiten',
                'ordering': ['nav_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='customsection',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.page', verbose_name='Zugeordnete Seite'),
        ),
    ]
