# Generated by Django 6.0.5 on 2026-05-12 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_add_page_model_and_page_fk_to_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitecontent',
            options={'ordering': ['page', 'section', 'order', 'key'], 'verbose_name': 'Seiteninhalt', 'verbose_name_plural': 'Seiteninhalte'},
        ),
        migrations.AlterUniqueTogether(
            name='sitecontent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_contents', to='content.page', verbose_name='Zugeordnete Seite'),
        ),
        migrations.AlterUniqueTogether(
            name='sitecontent',
            unique_together={('page', 'section', 'key')},
        ),
    ]
