# Generated by Django 6.0.5 on 2026-05-12 17:22

import django.db.models.deletion
from django.db import migrations, models


def create_default_page_and_assign_sections(apps, schema_editor):
    """Create a default page and assign all sections without a page to it."""
    Page = apps.get_model('content', 'Page')
    CustomSection = apps.get_model('content', 'CustomSection')

    # Create default page if sections exist without a page
    sections_without_page = CustomSection.objects.filter(page__isnull=True)
    if sections_without_page.exists():
        default_page, created = Page.objects.get_or_create(
            slug='default',
            defaults={
                'title': 'Default Page',
                'template': 'default',
                'is_published': False,
                'show_in_nav': False,
                'nav_order': 0,
            }
        )
        # Assign all sections without a page to the default page
        sections_without_page.update(page=default_page)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_sitecontent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customsection',
            name='site_contents',
        ),
        migrations.RunPython(create_default_page_and_assign_sections),
        migrations.AlterField(
            model_name='customsection',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.page', verbose_name='Zugeordnete Seite'),
        ),
    ]
